 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/keywords", type: :request do
  # Keyword. As you add validations to Keyword, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Keyword.create! valid_attributes
      get keywords_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      keyword = Keyword.create! valid_attributes
      get keyword_url(keyword)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_keyword_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      keyword = Keyword.create! valid_attributes
      get edit_keyword_url(keyword)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Keyword" do
        expect {
          post keywords_url, params: { keyword: valid_attributes }
        }.to change(Keyword, :count).by(1)
      end

      it "redirects to the created keyword" do
        post keywords_url, params: { keyword: valid_attributes }
        expect(response).to redirect_to(keyword_url(Keyword.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Keyword" do
        expect {
          post keywords_url, params: { keyword: invalid_attributes }
        }.to change(Keyword, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post keywords_url, params: { keyword: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested keyword" do
        keyword = Keyword.create! valid_attributes
        patch keyword_url(keyword), params: { keyword: new_attributes }
        keyword.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the keyword" do
        keyword = Keyword.create! valid_attributes
        patch keyword_url(keyword), params: { keyword: new_attributes }
        keyword.reload
        expect(response).to redirect_to(keyword_url(keyword))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        keyword = Keyword.create! valid_attributes
        patch keyword_url(keyword), params: { keyword: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested keyword" do
      keyword = Keyword.create! valid_attributes
      expect {
        delete keyword_url(keyword)
      }.to change(Keyword, :count).by(-1)
    end

    it "redirects to the keywords list" do
      keyword = Keyword.create! valid_attributes
      delete keyword_url(keyword)
      expect(response).to redirect_to(keywords_url)
    end
  end
end
